import Ember from 'ember';

const mockModel = [
      { "id": 1,
        "event": "EmberConf 2017",
        "type": "conference",
        "status": "done",
        "title": "Animate the Web with Ember.js",
        "date": "2017/03/28",
        "imgUrl": "assets/batguy.png",
        "videoUrl": "https://www.youtube.com/watch?v=wFJPIjRTIVU",
        "slidesUrl": "https://jessica-jordan.github.io/animate-the-web-with-emberjs/#/",
        "desc": "Were you a fan of animated cartoons as a kid, and wondered if one day you could create your own? Here's the great news: you can! Using open web standards and Ember.js you're able to create frame-by-frame animations—and even to make them interactive! This talk will explain why open web standards are more important than ever for creating animated content. We'll see how we can leverage the power of HTML5 Canvas in Ember efficiently and how to make animations interactive with the support of actions.",
        "location": "Portland, OR, US"
      },
      { "id": 2,
        "event": "jsDay 2017",
        "type": "conference",
        "status": "done",
        "title": "Animate the Web with Ember.js",
        "date": "2017/05/10",
        "imgUrl": "assets/90sinternet.gif",
        "slidesUrl": "https://jessica-jordan.github.io/animate-the-web-with-emberjs/#/",
        "desc": "Were you a fan of animated cartoons as a kid, and wondered if one day you could create your own? Here's the great news: you can! Using open web standards and Ember.js you're able to create frame-by-frame animations—and even to make them interactive! This talk will explain why open web standards are more important than ever for creating animated content. We'll see how we can leverage the power of HTML5 Canvas in Ember efficiently and how to make animations interactive with the support of actions.",
        "location": "Verona, Italy"
      },
      { "id": 3,
        "event": "Front 2017",
        "title": "Animate the Web with Ember.js",
        "type": "conference",
        "status": "done",
        "date": "2017/06/24",
        "imgUrl": "assets/kim.gif",
        "videoUrl": "https://www.youtube.com/watch?v=n-z7En2O9mQ",
        "slidesUrl": "https://jessica-jordan.github.io/animate-the-web-with-emberjs/#/",
        "desc": "Were you a fan of animated cartoons as a kid, and wondered if one day you could create your own? Here's the great news: you can! Using open web standards and Ember.js you're able to create frame-by-frame animations—and even to make them interactive! This talk will explain why open web standards are more important than ever for creating animated content. We'll see how we can leverage the power of HTML5 Canvas in Ember efficiently and how to make animations interactive with the support of actions.",
        "location": "Madrid, Spain"
      },
      { "id": 4,
        "event": "EmberCamp London 2017",
        "title": "The Modern State of Web Components - A Glimmer of Hope",
        "date": "2017/07/11",
        "type": "conference",
        "status": "done",
        "imgUrl": "assets/glimmerpic.jpg",
        "videoUrl": "https://www.youtube.com/watch?v=OzFgDBJcWuU",
        "slidesUrl": "https://speakerdeck.com/jessicajordanjs/the-modern-state-of-web-components-a-glimmer-of-hope",
        "desc": "The browser support of web components has been getting increasingly better over the past few years and besides other component libraries, including Polymer or X-Tag, the Ember community presents its own new library - Glimmer.js - enabling you to create easy-to-use web components today. In this talk we will cover browser support, polyfilling and how Glimmer.js can help us to create reusable components for our web apps today. Alongside a component demo we will see how we can build and ship our Glimmer based web components and have a look at promising API developments for the future.",
        "location": "London, United Kingdom"
      },
      { "id": 5,
        "event": "RuhrJS 2017",
        "title": "Animate the Web with Ember.js",
        "date": "2017/10/14",
        "type": "conference",
        "status": "upcoming",
        "imgUrl": "assets/horse.gif",
        "confUrl": "https://ruhrjs.de/speakers/jessica-jordan",
        "desc": "Were you a fan of animated cartoons as a kid, and wondered if one day you could create your own? Here's the great news: you can! Using open web standards and Ember.js you're able to create frame-by-frame animations—and even to make them interactive! This talk will explain why open web standards are more important than ever for creating animated content. We'll see how we can leverage the power of HTML5 Canvas in Ember efficiently and how to make animations interactive with the support of actions.",
        "location": "Bochum, Germany"
      },
      { "id": 6,
        "event": "EmberFest 2017",
        "title": "Testing against Time - Meaningful testing when timing matters",
        "date": "2017/10/13",
        "type": "conference",
        "status": "upcoming",
        "confUrl": "https://emberfest.eu/schedule/#jessica-jordan",
        "imgUrl": "assets/athlete2.gif",
        "location": "Berlin, Germany"
      },
      { "id": 7,
        "event": "International JavaScript Conference 2017",
        "title": "A Glimmer of Hope - Creating Modern Web Components with Glimmer.js",
        "date": "2017/10/15",
        "type": "conference",
        "status": "upcoming",
        "confUrl": "https://javascript-conference.com/speaker/jessica-jordan/",
        "imgUrl": "assets/webcomponents.svg",
        "desc": "The browser support of web components has been getting increasingly better over the past few years and besides other component libraries, including Polymer or X-Tag, the Ember community presents its own new library - Glimmer.js - enabling you to create easy-to-use web components today. In this talk we will cover browser support, polyfilling and how Glimmer.js can help us to create reusable components for our web apps today. Alongside a component demo we will see how we can build and ship our Glimmer based web components and have a look at promising API developments for the future.",
        "location": "Munich, Germany"
      },
      { "id": 8,
        "event": "Ember London Meetup November 2016",
        "title": "Leveraging HTML5 animations using CSS3, Ember.js and friends",
        "date": "2016/11/10",
        "type": "meetup",
        "status": "done",
        "imgUrl": "assets/jugendkim-cut.jpg",
        "videoUrl": "https://pusher.com/sessions/meetup/ember-london/leveraging-html5-animations-using-css3-emberjs-and-friends",
        "location": "London, United Kingdom"
      },
     ];
export default Ember.Route.extend({
  model(){
    return mockModel;
  }
});
